version: '3'
services:
  db:
    image: postgres:10.8
    container_name: postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/etl-go-project
    depends_on:
      - db
    links:
      - db